Fix a race condition in StubAccountInfo
This:
```
======================================================================
ERROR: test_upload_large_resume_file_info_does_not_match (test_bucket.TestUpload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/test/test_bucket.py", line 399, in test_upload_large_resume_file_info_does_not_match
    file_info = self.bucket.upload_bytes(
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/bucket.py", line 265, in upload_bytes
    return self.upload(upload_source, file_name, content_type, file_infos, progress_listener)
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/bucket.py", line 326, in upload
    return self._upload_large_file(
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/bucket.py", line 403, in _upload_large_file
    part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/utils.py", line 56, in interruptible_get_result
    return future.result(timeout=1.0)
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/utils.py", line 56, in interruptible_get_result
    return future.result(timeout=1.0)
  File "/home/travis/.virtualenv/jython/Lib/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/travis/.virtualenv/jython/Lib/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/bucket.py", line 477, in _upload_part
    upload_url, upload_auth_token = self._get_upload_part_data(file_id)
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/b2/bucket.py", line 527, in _get_upload_part_data
    upload_url, upload_auth_token = account_info.take_large_file_upload_url(file_id)
  File "/home/travis/build/Backblaze/B2_Command_Line_Tool/test/stub_account_info.py", line 100, in take_large_file_upload_url
    return upload_urls.pop()
IndexError: pop from empty list
```
was found [here](https://travis-ci.org/Backblaze/B2_Command_Line_Tool/jobs/142920282) by our new Jython target.

Jython has no GIL and it doesn't switch threads every set amount of instructions, so the concurrency there is "more real" than in CPython.